version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  hydrobot:
    build: .
    command: python main.py
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data:
